# Global variables to set the printing for each generation
PRINT_FITNESS_INDIVIDUALS = True
PRINT_INDIVIDUALS_LAYERS = True
PRINT_ACCURACY_INDIVIDUALS = False
PRINT_INDIVIDUALS_FEATURES = True
PRINT_F1_INDIVIDUALS = True
PRINT_RECALL_INDIVIDUALS = True
PRINT_PRECISION_INDIVIDUALS = True
